services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "${DATABASE_URL_DOCKER}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
